spring:
  application:
    name: Polling-Voting
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8080
app:
  db:
    host: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    db-name: ${DB_NAME}

